[0m01:51:12.922661 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc3ed1a6c30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc3ed1d3980>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc3ebec2090>]}


============================== 01:51:12.926763 | fc0c8958-cf39-4592-a324-cec2034480a4 ==============================
[0m01:51:12.926763 [info ] [MainThread]: Running with dbt=1.10.8
[0m01:51:12.927483 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/gitpod/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt init', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m01:51:36.299871 [debug] [MainThread]: Starter project path: /workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dbt/include/starter_project
[0m01:51:36.304055 [info ] [MainThread]: 
Your new dbt project "dbtCustomerOrders" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m01:51:36.304650 [info ] [MainThread]: Setting up your profile.
[0m01:52:04.419610 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 51.569805, "process_in_blocks": "0", "process_kernel_time": 0.216443, "process_mem_max_rss": "104512", "process_out_blocks": "72", "process_user_time": 1.803695}
[0m01:52:04.420528 [debug] [MainThread]: Command `dbt init` succeeded at 01:52:04.420384 after 51.57 seconds
[0m01:52:04.421093 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc3eb7bce30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc3ec387ec0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc3ebff9760>]}
[0m01:52:04.421723 [debug] [MainThread]: Flushing usage events
[0m01:52:05.057843 [debug] [MainThread]: An error was encountered while trying to flush usage events
